### ISSUE TITLE
东西很不错，但是有段代码好像没啥用？

### ISSUE THREAD

**Issue by jasperchou** [hydreamit/HyCycleView#1]
![image](https://user-images.githubusercontent.com/5203708/96213105-c641f380-0faa-11eb-9b6a-feedb28035a7.png)

中间那段代码注释掉貌似没啥区别，gesture重复加到view上面应该是只认最后一个？
（我试过注释掉了，目前没有问题）

**Comment by hydreamit** [comment]
多余的代码 之前版本忘删了
