### ISSUE TITLE
重设不同高度的header，offset不正常

### ISSUE THREAD

**Issue by jasperchou** [hydreamit/HyCycleView#2]
现象：重设header之后，header向上移动了高度变化的差值。也就是一部分header向上滑了，不过可以滑回来，没有其他问题。

![image](https://user-images.githubusercontent.com/5203708/96247513-ce1a8b80-0fdc-11eb-9693-48ad6dea595a.png)

debug可以发现，header的frame的Y发生了变化。我是打开controller就重设不同高度的header，没有滚动操作。单步调试发现是因为设置contentInset触发了监听，所以getCurrentOffset里面计算出现了问题。

目前临时解决方案：我是重设header之后把子scrollview滚动到顶部。

希望作者有更好的解决方案。感谢。

**Comment by hydreamit** [comment]
设置的代码和现象截屏有吗？

**Comment by jasperchou** [comment]
![image](https://user-images.githubusercontent.com/5203708/96825305-5d072800-1463-11eb-862a-e3df153eb1d0.png)

这是重设header代码
现象就是重设之后，scrollview没有滚动到顶部。看代码可以看到，我把他滚动到了顶部。

**Comment by hydreamit** [comment]
重设header没有超过条件临界点，默认是不会重设offset，根据自己的需求，也可以调用
- (void)updateContentOffSetY:(CGFloat)contentOffsetY animation:(BOOL)flag;

**Comment by jasperchou** [comment]
原来是这样子啊。谢谢回复。
