### ISSUE TITLE
如果需要更改SegmentView的标题该怎么做？

### ISSUE THREAD

**Issue by maoweipengft** [hydreamit/HyCycleView#4]

**Comment by hydreamit** [comment]
修改 configure 对应block数据源 
然后调用 - (void)reloadData;

**Comment by maoweipengft** [comment]
调用reloadData之后下划线会消失，需要滑动一下或者点击一下之后切换了item才会重新显示

**Comment by hydreamit** [comment]
什么情况下出现的呢, 可以看看代码嘛?

可以参照下面demo里的测试代码
@implementation CyclePageViewBaseDemoController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    self.view.backgroundColor = UIColor.whiteColor;
    self.titleArray = @[@"NBA", @"国际足球", @"中国篮球", @"跑步",@"欧洲杯", @"欧冠" ,@"英超", @"西甲", @"意甲"];
    [self.view addSubview:self.scrollView];
    [self.cyclePageView reloadData];
    
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        self.titleArray = @[@"NBA_1", @"国际足球_2", @"中国篮球_3"];
        [self.segmentView reloadData];
        [self.cyclePageView reloadData];
    });
}

**Comment by maoweipengft** [comment]
在网络请求完成后，block的回调中使用了[weakself.segmentView reloadData];，就会发生

**Comment by hydreamit** [comment]
已修复
