### ISSUE TITLE
如何在headerview悬浮后pageview才能滑动

### ISSUE THREAD

**Issue by maoweipengft** [hydreamit/HyCycleView#5]
你好请问一下 如何在headerview悬浮后之后pageview才开始能滑动里面的内容，我在看demo的时候是能这样的，但是不知道为什么当我把数据接入进去之后就不能这样了，这个跟哪个参数，或者是哪个代理有关吗，我是scrollview嵌套的collectionview

**Comment by hydreamit** [comment]
看不出什么问题，数据怎么接入的？外层提供的分页view是collectionview？

**Comment by maoweipengft** [comment]
分页是个viewcontroller，里面放了collectionview，我看了demo里面抖音->我那个界面，发现pageview是个collectionview的话是没这样的问题，但是pageview是个viewcontroll就会这样segment没悬浮pageview的内容就能滑动了，大大有没有什么方法可让pageview是viewcontroller也能等segment悬浮之后才可以滑动呢？我相信这也是绝大多数场景会用到的

**Comment by hydreamit** [comment]
给pageview提供的分页view 换成控制器view的colletionView，
demo控制器是UITableViewController，控制器的View是tableview
提供的分页View不是scorllView的话，滑动内容高度是view的高度

在控制器里面实现协议方法，提供分页View为你对应的ColletionView
- (void)configCyclePageView:(HyCycleViewProvider<HyCyclePageView *> *)provider index:(NSInteger)index {
   self.index = index;
    // 主动设置引用
    // provider.retainProvider = YES;
    // __weak typeof(self) weakSelf = self;
    // block 自动引用
    [provider view:^UIView * _Nonnull(HyCyclePageView * _Nonnull cycleView) {
        return self.colletionView;
    }];
}

**Comment by maoweipengft** [comment]
这样写分页的colletionView显示不出来了 强引用也显不出来

**Comment by hydreamit** [comment]
控制器里的colletionView是懒加载的嘛？colletionView可能拿到的是nil
如果不是懒加载， 在控制器里的 viewDidLoad初始化的， 
在- (void)configCyclePageView:(HyCycleViewProvider<HyCyclePageView *> *)provider index:(NSInteger)index 协议方法里调用下【self view】, 这样才会走控制器里的viewDidLoad 方法， 这里控制器只是作为pageCycleView的数据源

**Comment by maoweipengft** [comment]
懒加载的，搞定了，感谢🙏🙏🙏

**Comment by maoweipengft** [comment]
换成懒加载也是不行，调用 【self view】也不行。这个滑动的问题是不是因为我在分页的控制器里写了scrolliew的代理导致的呢
